export const project_template1 = {
  id: 1,
  name: "project-template1",
  title: ["Project", "Template", "1"],
  subtitle: ["A short description of the project", "goes here. Tell people how", "awesome this project is, who it's", "for and how it helps them, and", "what you learned from it."],
  author: "Cameron Jack",
  date: "2024-06-04",
  link: "/projects/project-template",
  text: {
    abstract: ["Lorem  ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod  tempor incididunt ut labore et dolore magna aliqua. Urna condimentum  mattis pellentesque id nibh tortor. Enim neque volutpat ac tincidunt  vitae semper quis lectus nulla. Leo vel orci porta non pulvinar neque.  Dignissim convallis aenean et tortor at risus viverra. Bibendum est  ultricies integer quis. Ac orci phasellus egestas tellus rutrum tellus  pellentesque eu. Eu augue ut lectus arcu bibendum at varius. Proin sed  libero enim sed faucibus turpis in eu mi. Enim ut sem viverra aliquet  eget."],
    introduction: ["Mattis pellentesque id nibh tortor id aliquet lectus proin nibh.  Varius sit amet mattis vulputate enim nulla aliquet. In nulla posuere  sollicitudin aliquam ultrices sagittis orci. Sit amet mauris commodo  quis imperdiet massa tincidunt nunc pulvinar. Lacus sed turpis tincidunt  id aliquet. Tempor commodo ullamcorper a lacus vestibulum. Tincidunt  tortor aliquam nulla facilisi cras fermentum. Non nisi est sit amet  facilisis magna. Quam id leo in vitae turpis. Mi in nulla posuere  sollicitudin aliquam ultrices sagittis orci. Suspendisse sed nisi lacus  sed viverra. Ac turpis egestas maecenas pharetra convallis posuere morbi  leo. Turpis egestas pretium aenean pharetra. Eu consequat ac felis  donec. Proin nibh nisl condimentum id."],
    main: [
      "Quisque egestas diam in arcu cursus euismod quis viverra. Fringilla  ut morbi tincidunt augue. Cras sed felis eget velit. Ultricies lacus sed  turpis tincidunt id aliquet risus feugiat. At varius vel pharetra vel.  Eu feugiat pretium nibh ipsum. Scelerisque fermentum dui faucibus in  ornare quam. Turpis egestas maecenas pharetra convallis posuere morbi  leo urna molestie. Orci nulla pellentesque dignissim enim sit. Dolor  purus non enim praesent. Egestas sed sed risus pretium quam vulputate  dignissim suspendisse. Ornare quam viverra orci sagittis eu. Mauris a  diam maecenas sed enim ut sem viverra aliquet. Elementum integer enim  neque volutpat ac tincidunt. Nisl pretium fusce id velit. In ante metus  dictum at tempor commodo ullamcorper a lacus.",
      "Id interdum velit laoreet id donec ultrices tincidunt arcu. Luctus  venenatis lectus magna fringilla urna. Facilisis volutpat est velit  egestas dui id ornare arcu odio. Cras ornare arcu dui vivamus arcu felis  bibendum ut. Egestas integer eget aliquet nibh praesent. At ultrices mi  tempus imperdiet nulla malesuada. In aliquam sem fringilla ut. Turpis  tincidunt id aliquet risus. Neque aliquam vestibulum morbi blandit  cursus risus. Consectetur adipiscing elit ut aliquam purus sit amet. Et  tortor consequat id porta nibh. Aliquet bibendum enim facilisis gravida  neque convallis a. Dui sapien eget mi proin sed libero enim sed. Enim ut  sem viverra aliquet eget. Duis ultricies lacus sed turpis tincidunt.  Urna et pharetra pharetra massa massa ultricies. In aliquam sem  fringilla ut morbi tincidunt augue interdum. Facilisi etiam dignissim  diam quis enim lobortis scelerisque fermentum.",
      "Diam phasellus vestibulum lorem sed risus. Lorem mollis aliquam ut  porttitor leo a. Eget velit aliquet sagittis id consectetur purus. Nulla  pharetra diam sit amet. Dignissim cras tincidunt lobortis feugiat  vivamus at augue eget arcu. Sollicitudin ac orci phasellus egestas  tellus rutrum tellus pellentesque eu. Porta lorem mollis aliquam ut.  Quisque sagittis purus sit amet volutpat. Suscipit tellus mauris a diam.  Condimentum id venenatis a condimentum. Cursus in hac habitasse platea  dictumst. Enim sit amet venenatis urna cursus eget nunc. Leo urna  molestie at elementum eu. Aliquam purus sit amet luctus.",
      "Quam nulla porttitor massa id neque aliquam vestibulum morbi. Donec  ultrices tincidunt arcu non sodales neque sodales ut. Donec massa sapien  faucibus et molestie ac feugiat sed lectus. Scelerisque purus semper  eget duis at tellus at urna condimentum. Integer vitae justo eget magna  fermentum iaculis eu non diam. Risus commodo viverra maecenas accumsan  lacus vel. Neque ornare aenean euismod elementum nisi quis eleifend  quam. Pellentesque massa placerat duis ultricies lacus sed turpis  tincidunt id. Aliquam ultrices sagittis orci a scelerisque purus semper  eget. Penatibus et magnis dis parturient montes nascetur ridiculus mus.  Quam elementum pulvinar etiam non quam. Nunc mattis enim ut tellus  elementum sagittis vitae. At quis risus sed vulputate odio ut. Ut tortor  pretium viverra suspendisse.",
      "Platea dictumst vestibulum rhoncus est  pellentesque. Amet consectetur adipiscing elit duis tristique  sollicitudin. Lacus vestibulum sed arcu non odio euismod lacinia at.  Faucibus interdum posuere lorem ipsum dolor sit. Volutpat consequat  mauris nunc congue nisi vitae suscipit tellus. Quis auctor elit sed  vulputate mi sit amet. Potenti nullam ac tortor vitae purus faucibus ornare. Lectus nulla at  volutpat diam ut venenatis tellus in. Nisl tincidunt eget nullam non  nisi est sit. Neque viverra justo nec ultrices dui sapien. Viverra nam  libero justo laoreet. Sit amet venenatis urna cursus eget nunc  scelerisque viverra mauris. Sit amet luctus venenatis lectus magna  fringilla urna porttitor. Nisl nunc mi ipsum faucibus vitae. Integer  quis auctor elit sed vulputate mi sit amet mauris. Feugiat pretium nibh  ipsum consequat. Cras pulvinar mattis nunc sed blandit libero. Netus et  malesuada fames ac.",
      "Molestie at elementum eu facilisis sed odio morbi quis commodo.  Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Leo  vel orci porta non pulvinar neque laoreet suspendisse. Nisi lacus sed  viverra tellus in hac. Quisque egestas diam in arcu cursus. Turpis  egestas integer eget aliquet nibh praesent tristique magna. Sit amet  massa vitae tortor condimentum lacinia quis vel. Id nibh tortor id  aliquet. Pellentesque adipiscing commodo elit at imperdiet dui accumsan  sit amet. Lacus sed viverra tellus in hac habitasse. Faucibus pulvinar  elementum integer enim neque volutpat ac tincidunt. Adipiscing elit ut  aliquam purus sit amet. Ut lectus arcu bibendum at varius vel pharetra  vel. Laoreet id donec ultrices tincidunt arcu non sodales.",
      "Nibh sit amet commodo nulla facilisi. Sapien et ligula ullamcorper  malesuada proin libero nunc. Sed velit dignissim sodales ut eu.  Ultricies mi quis hendrerit dolor magna eget. Aenean euismod elementum  nisi quis eleifend quam adipiscing vitae proin. Nullam ac tortor vitae  purus faucibus ornare suspendisse. Pharetra convallis posuere morbi leo  urna molestie at elementum eu. Massa massa ultricies mi quis hendrerit  dolor. Proin nibh nisl condimentum id venenatis a condimentum vitae  sapien. Id velit ut tortor pretium viverra suspendisse potenti. Commodo  sed egestas egestas fringilla. Ut diam quam nulla porttitor massa id  neque. A diam sollicitudin tempor id. Rutrum quisque non tellus orci ac  auctor augue mauris. Eleifend mi in nulla posuere sollicitudin aliquam  ultrices sagittis orci. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem.  Aliquam etiam erat velit scelerisque in dictum non consectetur a. In  vitae turpis massa sed elementum. Lorem dolor sed viverra ipsum nunc  aliquet bibendum. Tincidunt nunc pulvinar sapien et ligula ullamcorper  malesuada. Amet est placerat in egestas erat imperdiet sed. Nisi porta  lorem mollis aliquam ut. Turpis in eu mi bibendum neque egestas congue  quisque. Dignissim diam quis enim lobortis scelerisque fermentum dui.  Tortor vitae purus faucibus ornare suspendisse sed. Libero justo laoreet  sit amet cursus sit amet dictum sit. Urna cursus eget nunc scelerisque  viverra mauris. Enim nec dui nunc mattis. Sapien eget mi proin sed  libero enim sed faucibus. Duis tristique sollicitudin nibh sit amet.  Sagittis vitae et leo duis ut diam quam nulla. Egestas egestas fringilla  phasellus faucibus scelerisque eleifend donec pretium vulputate. Montes  nascetur ridiculus mus mauris. Semper viverra nam libero justo laoreet  sit.",
      "Nibh tellus molestie nunc non blandit massa enim nec. Tellus id  interdum velit laoreet id donec. Tempor nec feugiat nisl pretium fusce  id velit ut tortor. Integer malesuada nunc vel risus commodo. Sapien  eget mi proin sed libero enim sed faucibus turpis. Feugiat sed lectus  vestibulum mattis ullamcorper velit sed ullamcorper morbi. Phasellus  faucibus scelerisque eleifend donec pretium vulputate sapien nec  sagittis. Integer vitae justo eget magna fermentum. Velit sed  ullamcorper morbi tincidunt ornare massa. Diam maecenas ultricies mi  eget mauris pharetra et ultrices. Sed arcu non odio euismod lacinia at.  Ut diam quam nulla porttitor massa id. Commodo quis imperdiet massa  tincidunt. Vitae congue mauris rhoncus aenean vel elit. Vitae suscipit  tellus mauris a diam maecenas sed enim ut. Molestie at elementum eu  facilisis sed odio. Ullamcorper malesuada proin libero nunc consequat  interdum varius sit amet. Sollicitudin ac orci phasellus egestas tellus  rutrum tellus. Ullamcorper velit sed ullamcorper morbi tincidunt ornare  massa eget egestas.",
    ],
      conclusion: [
      "Quisque egestas diam in arcu cursus euismod. Sit amet aliquam id diam  maecenas ultricies mi. Id venenatis a condimentum vitae. Id donec  ultrices tincidunt arcu non. Proin sed libero enim sed faucibus turpis  in eu. Fringilla est ullamcorper eget nulla. Viverra suspendisse potenti  nullam ac tortor vitae purus faucibus. Orci porta non pulvinar neque.  Nec ullamcorper sit amet risus nullam. Odio facilisis mauris sit amet  massa vitae tortor condimentum lacinia. Sed euismod nisi porta lorem  mollis aliquam. Nec feugiat nisl pretium fusce id velit ut tortor  pretium. Massa sapien faucibus et molestie. Lobortis mattis aliquam  faucibus purus in massa tempor nec feugiat. Nunc lobortis mattis aliquam  faucibus purus in. Quam viverra orci sagittis eu volutpat odio  facilisis mauris. Amet est placerat in egestas erat imperdiet sed. Nec  nam aliquam sem et tortor. Vulputate dignissim suspendisse in est ante.",
      "Dolor sit amet consectetur adipiscing elit duis tristique. Arcu ac  tortor dignissim convallis aenean. Auctor urna nunc id cursus metus  aliquam eleifend. Neque aliquam vestibulum morbi blandit cursus risus  at. A iaculis at erat pellentesque adipiscing commodo. In dictum non  consectetur a erat nam. Sit amet mauris commodo quis imperdiet massa  tincidunt nunc. Diam ut venenatis tellus in metus vulputate eu  scelerisque felis. Lectus mauris ultrices eros in. Dolor magna eget est  lorem ipsum dolor. Ac feugiat sed lectus vestibulum mattis ullamcorper  velit sed ullamcorper. Sit amet mattis vulputate enim nulla.",
      "Lobortis elementum nibh tellus molestie nunc non. Urna cursus eget  nunc scelerisque. Ultricies mi quis hendrerit dolor magna eget est. In  hendrerit gravida rutrum quisque non tellus. Sit amet venenatis urna  cursus eget nunc scelerisque. Elementum nisi quis eleifend quam  adipiscing vitae proin. Dolor sit amet consectetur adipiscing elit  pellentesque habitant morbi. Sit amet nisl purus in. Sit amet aliquam id  diam. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi.  Accumsan sit amet nulla facilisi morbi tempus. Tincidunt lobortis  feugiat vivamus at augue eget arcu dictum varius.",
    ]
  },
  bibliography: [
    {
      id: 0,
      author: "Donald E. Knuth",
      source: "The Art of Computer Programming, p. 109",
      copyright: "Addison-Wesley, 1968",
      accessedOn: "2024-06-02",
    },
    {
      id: 1,
      author: "Donald E. Knuth",
      source: "The Art of Computer Programming, p. 109",
      copyright: "Addison-Wesley, 1968",
      accessedOn: "2024-06-02",
    },
    {
      id: 2,
      author: "Donald E. Knuth",
      source: "The Art of Computer Programming, p. 109",
      copyright: "Addison-Wesley, 1968",
      accessedOn: "2024-06-02",
    },
  ]
}